defmodule StacApiWeb.CatalogJSON do
  @moduledoc """
  STAC JSON representation of a `StacApi.Data.Catalog`.

  Single source of truth for the catalog payload returned by
  `StacApiWeb.CatalogsCrudController` (create / show / update / patch / index).
  Links are generated by the caller — see `StacApiWeb.DynamicLinkGenerator` —
  because the link set depends on the request (custom links from the body on
  writes, persisted links on reads).
  """

  alias StacApi.Data.Catalog

  @doc """
  Render a catalog as a STAC Catalog object.
  """
  def to_stac(%Catalog{} = catalog, links) do
    %{
      stac_version: catalog.stac_version || "1.0.0",
      type: "Catalog",
      id: catalog.id,
      title: catalog.title,
      description: catalog.description,
      extent: catalog.extent,
      links: links
    }
  end
end
