defmodule StacApiWeb.CollectionJSON do
  @moduledoc """
  STAC JSON representation of a `StacApi.Data.Collection`.

  Single source of truth for the collection payload returned by
  `StacApiWeb.CollectionsCrudController` (create / show / update / patch / index).
  Links are generated by the caller — see `StacApiWeb.DynamicLinkGenerator` —
  because the link set depends on the request (custom links from the body on
  writes, persisted links on reads).
  """

  alias StacApi.Data.Collection
  alias StacApiWeb.STACDateTime

  @doc """
  Render a collection as a STAC Collection object.

  Options:

    * `:drop_nils` — omit fields whose value is `nil`. The read actions (`show`,
      `index`) have always done this while the write actions have not, so the
      flag preserves that existing difference rather than silently changing
      either response. Worth unifying separately.
  """
  def to_stac(collection, links, opts \\ [])

  def to_stac(%Collection{} = collection, links, opts) do
    stac = %{
      stac_version: collection.stac_version || "1.0.0",
      type: "Collection",
      id: collection.id,
      title: collection.title,
      description: collection.description,
      license: collection.license,
      extent: collection.extent,
      summaries: collection.summaries,
      keywords: collection.keywords,
      providers: collection.providers,
      stac_extensions: collection.stac_extensions || [],
      catalog_id: collection.catalog_id,
      created: STACDateTime.to_rfc3339(collection.inserted_at),
      updated: STACDateTime.to_rfc3339(collection.updated_at),
      links: links
    }

    if Keyword.get(opts, :drop_nils, false) do
      stac |> Enum.reject(fn {_k, v} -> is_nil(v) end) |> Enum.into(%{})
    else
      stac
    end
  end
end
